### ISSUE TITLE
Updating model URLs broken

### ISSUE THREAD

**Issue by adam-murray** [divio/djangocms-url-manager#27]
When updating a model it is not possible to change the type of URL. i.e. if a saved model instance is linked to a page it is not possible to change to a manual URL. - if this is an intended feature there should be feedback.

**Comment by adam-murray** [comment]
This is due to the expectation that one (and only one) of the types of URL should be populated. The get_url method in models.py returns the url corresponding to the last type checked for, meaning it may be incorrect. 

A custom save method would fix this.

**Comment by adam-murray** [comment]
PR:
https://github.com/divio/djangocms-url-manager/pull/29

**Comment by Aiky30** [comment]
Fix merged
