### ISSUE TITLE
Test failing on release build (compatibility issue with djangocms <4.0.x)

### ISSUE THREAD

**Issue by adam-murray** [divio/djangocms-url-manager#30]
The tests for URL Manager are currently failing: FAILED (failures=8, errors=19, skipped=15)

**Comment by adam-murray** [comment]
https://github.com/divio/djangocms-url-manager/pull/31

**Comment by jonathan-s** [comment]
can be closed now.

**Comment by adam-murray** [comment]
Resolved.
